name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 🗃️ Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: 📦 Install dependencies
        run: bun install

      - name: 🔍 Lint code
        continue-on-error: true
        run: bun run lint

      - name: 🧪 Run tests
        continue-on-error: true
        run: bun run test

      - name: 🏗️ Build project
        run: bun run build
